<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>STSY.Identity.Google</PackageId>
    <Version>1.0.0</Version>
    <Authors>sarya tulimat</Authors>
    <Company>ST</Company>
    <PackageTags>utilities</PackageTags>
    <RepositoryUrl>https://github.com/Mohammad-Sarya-Tulimat/STSY.Identity</RepositoryUrl>
    <Description>shared library used on my projects.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STSY.Identity.Abstraction\STSY.Identity.Abstraction.csproj" />
  </ItemGroup>

</Project>
