using STSY.Identity.Abstraction.Models.Output;
using System.Threading;
using System.Threading.Tasks;

namespace STSY.Identity.Abstraction.Contract.Managers
{
    public interface IPasswordManager
    {
        /// <summary>
        ///  Generates a password reset token for the specified user.
        /// </summary>
        /// <param name="userId">The ID of the user for whom to generate the password reset token.</param>
        /// <param name="cancellationToken">A cancellation token.</param>
        /// <returns>The generated password reset token.</returns>
        /// <exception cref="System.ArgumentNullException"></exception>  
        /// <exception cref="Exeptions.ResourceNotFoundException"></exception>" 
        /// <exception cref="Exeptions.STSYIdentityException">general identity exception</exception>" 
        Task<string> GeneratePasswordResetTokenAsync(string userId, CancellationToken cancellationToken);
        /// <summary>
        ///  reset user password using reset token generated by GeneratePasswordResetTokenAsync method
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="resetToken">generated by GeneratePasswordResetTokenAsync</param>
        /// <param name="newPassword">the new password to set for the user</param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        /// <exception cref="System.ArgumentNullException"></exception>  
        /// <exception cref="Exeptions.ResourceNotFoundException"></exception>" 
        /// <exception cref="Exeptions.STSYIdentityException">general identity exception</exception>" 
        Task<STSYIdentityResult> ResetPasswordAsync(string userId, string resetToken, string newPassword, CancellationToken cancellationToken);
        /// <summary>
        /// 
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="newpassword">the new password to set for the user</param>
        /// <param name="oldpassword">the old password to verify before changing to the new password</param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        /// <exception cref="System.ArgumentNullException"></exception>  
        /// <exception cref="Exeptions.ResourceNotFoundException"></exception>"
        /// <exception cref="Exeptions.STSYIdentityException">general identity exception</exception>"  
        Task<STSYIdentityResult> ChangeUserPasswordAsync(string userId, string newpassword, string oldpassword, CancellationToken cancellationToken);
    }
}
